### PR TITLE
‎

### PR DESCRIPTION
**Pull request by ghost**
.

### CODE REVIEW

**Comment by gIhost** [comment]
Hi @atumanian 

Unfortunately, all my accounts were suspended, so I couldn't answer your question

**Comment by gIhost** [comment]
>  Sorry, I don't understand how these formulas are related to the PRs in question.

https://hy.wikipedia.org/wiki/Անվերջ_փոքր
The formula was about Infinitesimal functional changes 
From my opinion , The SF problem is unsolvable because this is not a search bug and is not related to any commit
I suggest you not to continue the discussion in marco repo because your account may be suspended
If you have any questions, ask here, I will be happy if I could answer your questions

**Comment by atumanian** [comment]
@gIhost 
I'm sorry to hear your accounts were suspended. If you give you email, we can talk by emails. Or you can open a topic on the Fishcooking forum.
Why do you think the "Update WDL model" commit provided infinitesimal functional changes?

**Comment by gIhost** [comment]
> Why do you think the "Update WDL model" commit provided infinitesimal functional changes?

https://github.com/glinscott/nnue-pytorch

Because nnue-pytorch created for old WDL model and Changing these values will cause wrong evaluation

**Comment by atumanian** [comment]
@ginkgo20 
Hi!
I don't know yet if your PR is a functional change. If it is, it requires testing on Fishtest. Have you observed whether you patch changes the bench number? Sorry for the rude comments of Vondele and some others. mhouppin's comment is right.

**Comment by ginkgo20** [comment]
I think also  joergoster's comment is right.

We have this assert in place 

```cpp
 assert(PvNode || (alpha == beta - 1)); 
```

 For `PV`Node should be `(beta - alpha) > 1` 
 
  For `NonPV`Node should be `(beta - alpha) = 1` 
  
My pull request was completely true even if it tested on Fishtest it passed.

Unfortunately, Vondele blocked me in Official_Stockfish just for creating this true commit.
 
 image

**Comment by ginkgo20** [comment]
@atumanian Also. I think joergoster's comment is right.

https://github.com/mcostalba/Stockfish/blob/7090d2561ae9ce3803bbc04319c4c93f756a6df2/src/search.cpp#LL1297C6-L1297C6

 For `PV`Node should be `(beta - alpha) > 1` 
 
  For `NonPV`Node should be `(beta - alpha) = 1` 
  
My pull request was completely true even if it tested on Fishtest it passed.

Unfortunately, Vondele blocked me in Official_Stockfish after creating this true commit.

**Comment by ginkgo20** [comment]
@atumanian I glad to see you again!
 
 For **PV** should be `(beta - alpha) > 1` 
 
  For **NonPV** should be `(beta - alpha) = 1` 
  
  We have this assert `assert(PvNode || (alpha == beta - 1))` in place:
  
```cpp
    template <NodeType nodeType>
  Value qsearch(Position& pos, Stack* ss, Value alpha, Value beta, Depth depth) {

    static_assert(nodeType != Root);
    constexpr bool PvNode = nodeType == PV;

    assert(alpha >= -VALUE_INFINITE && alpha < beta && beta <= VALUE_INFINITE);
    assert(PvNode || (alpha == beta - 1));
    assert(depth <= 0);
```

> Sorry for the rude comments of Vondele and some others.

Unfortunately, After creating this pull request, Vondele blocked me in Official_Stockfish.

**Comment by ginkgo20** [comment]
@atumanian This is my last comment for you, I wanted to create a topic on FishCooking but you did not answer me.

I don't know that what was you goal?! but It seems that you don't like to work together. 

Thank you for everything you do

Good Luck

**Comment by atumanian** [comment]
@ginkgo20 
Sorry for not answering earlier. I my quite busy now. If you want to create a topic on FishCooking, I can try to help you.

**Comment by ginkgo20** [comment]
@atumanian If you want to help me ,For start: send a comment in here :

[https://github.com/glinscott/nnue-pytorch/issues/245](/glinscott/nnue-pytorch/issues/245)

Recently, I created a true issue in nnue-pytorch but sopel97 closed it and blocked me without just saying a word!!!

This can be a good proof for Fishcooking topic in the future.

**Comment by atumanian** [comment]
@ginkgo20 
What kind of comment should I send? Report that you were blocked?

**Comment by ginkgo20** [comment]
@atumanian ,I have a better idea instead of sending comment.

You create a new issue in **nnue-pytorch** with similar title and the same contents ,

**If  Sopel97 closed it or blocked you, we can report it in your **FishCooking** topic.**

https://groups.google.com/g/fishcooking/c/e05Imm5ivqE

**Comment by atumanian** [comment]
@ginkgo20 
Sorry, I don't have much spare time to delve into these issues. You are free to report the block in FishCooking anyway. I currently don't see any point in commenting your issue or creating a new one, because I'm currently not interested in developing the project and blocked in official-stockfish like you.

**Comment by ginkgo20** [comment]
OK , Please write comment in my issue on nnue-pytorch asking for the reason for blocking.

**Comment by ginkgo20** [comment]
@atumanian Please let me know if you don't want to work together. You are not busy but I don't know "what is your goal?"

Although I love you ❤️ , but this is not a good reason to wait you forever

**Comment by atumanian** [comment]
@ginkgo20 
What you mean by working together? Working on what?

**Comment by ginkgo20** [comment]
@atumanian Thanks but you but you mention this link please delete this issue

**Comment by ginkgo20** [comment]
or make private this repo

**Comment by atumanian** [comment]
@ginkgo20
What you mean by working together? Working on what? If you want to work on a chess engine then, sorry, I don't have enough time now. You can still ask me and I'll try to give advice out of my experience.
I have written the comment you asked.
By the way, why do you write to me here and not on my email? It's not very convenient for me to talk on an unrelated GitHub repository. Don't you know how to create an email account?

**Comment by atumanian** [comment]
Sorry, I don't know how to make a repository private or delete a PR. But if you wrote to me privately (on email or Discord) there wouldn't be such inconveniences.

**Comment by ginkgo20** [comment]
I create a private repo now

**Comment by ginkgo20** [comment]
delete this whole repo

**Comment by EarlyEdition** [comment]
@atumanian Are you here?

**Comment by atumanian** [comment]
Yes, I am here. Who are you?
17 марта 2025, 04:09:07, От "EarlyEdition" ***@***.***>:
@atumanian Are you here?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
EarlyEdition left a comment (atumanian/Spoon-Knife#1)
@atumanian Are you here?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

--=-WywhOJNO+O4tPzOJ0Urb
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: base64

PGh0bWw+PGJvZHk+PHNwYW4gc3R5bGU9ImRpc3BsYXk6YmxvY2s7IiBjbGFzcz0ieGZtXzkyMjI5
MTU0Ij48ZGl2PjxzcGFuIHN0eWxlPSJmb250LXNpemU6MTJwdDtsaW5lLWhlaWdodDoxNHB0O2Zv
bnQtZmFtaWx5OkFyaWFsOyIgY2xhc3M9InhmbWMxIj5ZZXMsIEkgYW0gaGVyZS4gV2hvIGFyZSB5
b3U/PC9zcGFuPjxici8+PC9kaXY+DQo8ZGl2Pjxici8+PC9kaXY+DQo8ZGl2PjxpPjxzcGFuIHN0
eWxlPSJmb250LXNpemU6MTBwdDtsaW5lLWhlaWdodDoxMnB0OyI+PHNwYW4gc3R5bGU9ImZvbnQt
ZmFtaWx5OkFyaWFsOyI+MTcg0LzQsNGA0YLQsCAyMDI1LCAwNDowOTowNywg0J7RgiAiRWFybHlF
ZGl0aW9uIiAmbHQ7PC9zcGFuPjxhIGhyZWY9Im1haWx0bzpub3RpZmljYXRpb25zQGdpdGh1Yi5j
b20iIHRhcmdldD0iX2JsYW5rIj48c3BhbiBzdHlsZT0iZm9udC1mYW1pbHk6QXJpYWw7Ij5ub3Rp
ZmljYXRpb25zQGdpdGh1Yi5jb208L3NwYW4+PC9hPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTpB
cmlhbDsiPiZndDs6PC9zcGFuPjwvc3Bhbj48L2k+PC9kaXY+DQo8ZGl2Pjxici8+PC9kaXY+DQo8
YmxvY2txdW90ZSBzdHlsZT0iYm9yZGVyLWxlZnQ6MXB4IHNvbGlkICNjY2NjY2M7bWFyZ2luOjBw
eCAwcHggMHB4IDAuOGV4O3BhZGRpbmctbGVmdDoxZXg7Ij4NCjxkaXYgc3R5bGU9ImRpc3BsYXk6
YmxvY2s7Ij48c3BhbiBzdHlsZT0iY29sb3I6dHJhbnNwYXJlbnQ7ZGlzcGxheTpub25lO2hlaWdo
dDowO21heC1oZWlnaHQ6MDttYXgtd2lkdGg6MDtvdmVyZmxvdzpoaWRkZW47d2lkdGg6MDsiPg0K
PGRpdj48YSBocmVmPSJodHRwczovL2dpdGh1Yi5jb20vYXR1bWFuaWFuIiB0YXJnZXQ9Il9ibGFu
ayIgcmVsPSJub3JlZmVycmVyIG5vb3BlbmVyIj5AYXR1bWFuaWFuPC9hPiBBcmUgeW91IGhlcmU/
PC9kaXY+DQo8ZGl2PjxzcGFuIHN0eWxlPSJmb250LXNpemU6c21hbGw7Y29sb3I6IzY2NjsiPuKA
lDxici8+UmVwbHkgdG8gdGhpcyBlbWFpbCBkaXJlY3RseSwgPGEgaHJlZj0iaHR0cHM6Ly9naXRo
dWIuY29tL2F0dW1hbmlhbi9TcG9vbi1LbmlmZS9wdWxsLzEjaXNzdWVjb21tZW50LTI3Mjc4NDk1
MTgiIHRhcmdldD0iX2JsYW5rIiByZWw9Im5vcmVmZXJyZXIgbm9vcGVuZXIiPnZpZXcgaXQgb24g
R2l0SHViPC9hPiwgb3IgPGEgaHJlZj0iaHR0cHM6Ly9naXRodWIuY29tL25vdGlmaWNhdGlvbnMv
dW5zdWJzY3JpYmUtYXV0aC9BRkpLUEZBNEJCMzczUU9QUlpKSjMzVDJVWVZFRkFWQ05GU002QUFB
QUFCWkVLV0wyV1ZISTJEU01WUVdJWDNMTVY0M09TTFRPTjJXS1EzUE5WV1dLM1RVSE1aRE9NUlhI
QTJEU05KUkhBIiB0YXJnZXQ9Il9ibGFuayIgcmVsPSJub3JlZmVycmVyIG5vb3BlbmVyIj51bnN1
YnNjcmliZTwvYT4uPGJyLz5Zb3UgYXJlIHJlY2VpdmluZyB0aGlzIGJlY2F1c2UgeW91IHdlcmUg
bWVudGlvbmVkLjxpbWcgc3JjPSJodHRwczovL2dpdGh1Yi5jb20vbm90aWZpY2F0aW9ucy9iZWFj
b24vQUZKS1BGSFdWUlpZNUY1UkFZQ1FSNFQyVVlWRUZBNUNORlNNNkFBQUFBQlpFS1dMMldXR0cz
M05OVlNXNDVDN09SNFhBWk5NSkZaWEc1TEZJTlhXMjNMRk5aMktVWTNQTlZXV0szVFVMNVVXSlRW
Q1M2WEM0LmdpZiIgaGVpZ2h0PSIxIiB3aWR0aD0iMSIgYWx0PSIiLz48L3NwYW4+PHNwYW4gc3R5
bGU9ImZvbnQtc2l6ZTowO2NvbG9yOnRyYW5zcGFyZW50O2Rpc3BsYXk6bm9uZTtvdmVyZmxvdzpo
aWRkZW47d2lkdGg6MDtoZWlnaHQ6MDttYXgtd2lkdGg6MDttYXgtaGVpZ2h0OjA7Ij5NZXNzYWdl
IElEOiAmbHQ7YXR1bWFuaWFuL1Nwb29uLUtuaWZlL3B1bGwvMS9jMjcyNzg0OTUxOEBnaXRodWIu
Y29tJmd0Ozwvc3Bhbj48L2Rpdj4NCg0KPC9zcGFuPg0KPGRpdiBzdHlsZT0iZGlzcGxheTpmbGV4
O3doaXRlLXNwYWNlOnByZS13cmFwOyI+PGltZyBhbHQ9IkVhcmx5RWRpdGlvbiIgaGVpZ2h0PSIy
MCIgd2lkdGg9IjIwIiBzdHlsZT0iYm9yZGVyLXJhZGl1czo1MCU7bWFyZ2luLXJpZ2h0OjRweDsi
IHNyYz0iaHR0cHM6Ly9hdmF0YXJzLmdpdGh1YnVzZXJjb250ZW50LmNvbS91LzI2OTcyND9zPTIw
JmFtcDt2PTQiLz48Yj5FYXJseUVkaXRpb248L2I+IGxlZnQgYSBjb21tZW50IDxhIGhyZWY9Imh0
dHBzOi8vZ2l0aHViLmNvbS9hdHVtYW5pYW4vU3Bvb24tS25pZmUvcHVsbC8xI2lzc3VlY29tbWVu
dC0yNzI3ODQ5NTE4IiB0YXJnZXQ9Il9ibGFuayIgcmVsPSJub3JlZmVycmVyIG5vb3BlbmVyIj4o
YXR1bWFuaWFuL1Nwb29uLUtuaWZlIzEpPC9hPjwvZGl2Pg0KPGRpdj48YSBocmVmPSJodHRwczov
L2dpdGh1Yi5jb20vYXR1bWFuaWFuIiB0YXJnZXQ9Il9ibGFuayIgcmVsPSJub3JlZmVycmVyIG5v
b3BlbmVyIj5AYXR1bWFuaWFuPC9hPiBBcmUgeW91IGhlcmU/PC9kaXY+DQo8ZGl2PjxzcGFuIHN0
eWxlPSJmb250LXNpemU6c21hbGw7Y29sb3I6IzY2NjsiPuKAlDxici8+UmVwbHkgdG8gdGhpcyBl
bWFpbCBkaXJlY3RseSwgPGEgaHJlZj0iaHR0cHM6Ly9naXRodWIuY29tL2F0dW1hbmlhbi9TcG9v
bi1LbmlmZS9wdWxsLzEjaXNzdWVjb21tZW50LTI3Mjc4NDk1MTgiIHRhcmdldD0iX2JsYW5rIiBy
ZWw9Im5vcmVmZXJyZXIgbm9vcGVuZXIiPnZpZXcgaXQgb24gR2l0SHViPC9hPiwgb3IgPGEgaHJl
Zj0iaHR0cHM6Ly9naXRodWIuY29tL25vdGlmaWNhdGlvbnMvdW5zdWJzY3JpYmUtYXV0aC9BRkpL
UEZBNEJCMzczUU9QUlpKSjMzVDJVWVZFRkFWQ05GU002QUFBQUFCWkVLV0wyV1ZISTJEU01WUVdJ
WDNMTVY0M09TTFRPTjJXS1EzUE5WV1dLM1RVSE1aRE9NUlhIQTJEU05KUkhBIiB0YXJnZXQ9Il9i
bGFuayIgcmVsPSJub3JlZmVycmVyIG5vb3BlbmVyIj51bnN1YnNjcmliZTwvYT4uPGJyLz5Zb3Ug
YXJlIHJlY2VpdmluZyB0aGlzIGJlY2F1c2UgeW91IHdlcmUgbWVudGlvbmVkLjxpbWcgc3JjPSJo
dHRwczovL2dpdGh1Yi5jb20vbm90aWZpY2F0aW9ucy9iZWFjb24vQUZKS1BGSFdWUlpZNUY1UkFZ
Q1FSNFQyVVlWRUZBNUNORlNNNkFBQUFBQlpFS1dMMldXR0czM05OVlNXNDVDN09SNFhBWk5NSkZa
WEc1TEZJTlhXMjNMRk5aMktVWTNQTlZXV0szVFVMNVVXSlRWQ1M2WEM0LmdpZiIgaGVpZ2h0PSIx
IiB3aWR0aD0iMSIgYWx0PSIiLz48L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZTowO2NvbG9y
OnRyYW5zcGFyZW50O2Rpc3BsYXk6bm9uZTtvdmVyZmxvdzpoaWRkZW47d2lkdGg6MDtoZWlnaHQ6
MDttYXgtd2lkdGg6MDttYXgtaGVpZ2h0OjA7Ij5NZXNzYWdlIElEOiAmbHQ7YXR1bWFuaWFuL1Nw
b29uLUtuaWZlL3B1bGwvMS9jMjcyNzg0OTUxOEBnaXRodWIuY29tJmd0Ozwvc3Bhbj48L2Rpdj4N
CjwvZGl2Pg0KPC9ibG9ja3F1b3RlPjwvc3Bhbj48L2JvZHk+PC9odG1sPg0K

--=-WywhOJNO+O4tPzOJ0Urb--

**Pull request closed without merging**
